
package gov.iti.backend.services.EmployeeService;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0-M2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeService", targetNamespace = "http://services.backend.iti.gov/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://services.backend.iti.gov/", className = "gov.iti.backend.services.EmployeeService.UpdateEmployee")
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://services.backend.iti.gov/", className = "gov.iti.backend.services.EmployeeService.UpdateEmployeeResponse")
    @Action(input = "http://services.backend.iti.gov/EmployeeService/updateEmployeeRequest", output = "http://services.backend.iti.gov/EmployeeService/updateEmployeeResponse")
    public void updateEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        EmployeeDto arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://services.backend.iti.gov/", className = "gov.iti.backend.services.EmployeeService.DeleteEmployee")
    @ResponseWrapper(localName = "deleteEmployeeResponse", targetNamespace = "http://services.backend.iti.gov/", className = "gov.iti.backend.services.EmployeeService.DeleteEmployeeResponse")
    @Action(input = "http://services.backend.iti.gov/EmployeeService/deleteEmployeeRequest", output = "http://services.backend.iti.gov/EmployeeService/deleteEmployeeResponse")
    public void deleteEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List&lt;gov.iti.backend.services.EmployeeService.EmployeeDto&gt;
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllEmployees", targetNamespace = "http://services.backend.iti.gov/", className = "gov.iti.backend.services.EmployeeService.GetAllEmployees")
    @ResponseWrapper(localName = "getAllEmployeesResponse", targetNamespace = "http://services.backend.iti.gov/", className = "gov.iti.backend.services.EmployeeService.GetAllEmployeesResponse")
    @Action(input = "http://services.backend.iti.gov/EmployeeService/getAllEmployeesRequest", output = "http://services.backend.iti.gov/EmployeeService/getAllEmployeesResponse")
    public List<EmployeeDto> getAllEmployees();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testing", targetNamespace = "http://services.backend.iti.gov/", className = "gov.iti.backend.services.EmployeeService.Testing")
    @ResponseWrapper(localName = "testingResponse", targetNamespace = "http://services.backend.iti.gov/", className = "gov.iti.backend.services.EmployeeService.TestingResponse")
    @Action(input = "http://services.backend.iti.gov/EmployeeService/testingRequest", output = "http://services.backend.iti.gov/EmployeeService/testingResponse")
    public String testing();

}
